#!/usr/bin/env bash
# Inventory sway's tiling-domain functions against what tiri cites.
#
# The point is a denominator that does not move. "Seeds clean" describes the fuzz budget as
# much as the compositor — raising SCRIPT_LEN from 14 to 28 turned five clean seeds into five
# divergent ones without a line of layout code changing. The number of sway functions in the
# domain does not move when we change a constant, so progress against it is progress.
#
# "Cited" means the name appears in tiri's source or design docs. That is the project's
# existing convention: a ported rule names the function it came from, so the port can be
# audited against the original. It proves a rule was read, not that it was read correctly —
# the fixtures are what prove that. Read this as coverage of the map, not of the ground.
set -euo pipefail

SWAY_SRC="${TIRI_PARITY_SWAY_SRC:-$HOME/Documentos/sway-master}"
OUT="${1:-docs/design/parity-inventory.md}"

if [ ! -d "$SWAY_SRC/sway/tree" ]; then
    echo "no sway source at $SWAY_SRC (set TIRI_PARITY_SWAY_SRC)" >&2
    exit 1
fi

work=$(mktemp -d); trap 'rm -rf "$work"' EXIT

# The domain: the tree itself, the arrange pass, and the commands that reshape them.
# Deliberately not seat device config, marks, scratchpad, criteria, bars or output layout.
grep -hoE '^[a-z_ ]*\**\b(container|workspace|arrange|view|seat)_[a-z_]+\(' \
    "$SWAY_SRC"/sway/tree/container.c \
    "$SWAY_SRC"/sway/tree/workspace.c \
    "$SWAY_SRC"/sway/tree/arrange.c \
    "$SWAY_SRC"/sway/commands/move.c \
    "$SWAY_SRC"/sway/commands/split.c \
    "$SWAY_SRC"/sway/commands/layout.c \
    "$SWAY_SRC"/sway/commands/focus.c \
    "$SWAY_SRC"/sway/commands/resize.c \
    "$SWAY_SRC"/sway/commands/fullscreen.c \
    "$SWAY_SRC"/sway/commands/swap.c \
  | grep -oE '\b(container|workspace|arrange|view|seat)_[a-z_]+' \
  | grep -vE '_(mark|marks|urgent|representation|title|title_bar|colors|damage|destroy|begin_destroy|update_iterator|for_each_child|for_each_container|handle_|iterator)$' \
  | grep -vE '^seat_(add|apply|configure|create|destroy|device|execute|idle|is_input|keyboard|pointer|remove|reset|send|tablet|update|node)' \
  | grep -vE '^workspace_(by_name|by_number|config|find_config|name_from|next_name|output_|get_initial|get_number|valid_on|auto_back)' \
  | sort -u > "$work/domain.txt"

grep -rhoE '\b(container|workspace|arrange|view|seat|cmd)_[a-z_]+\b' src/ docs/design/ 2>/dev/null \
  | sort -u > "$work/cited.txt"

comm -12 "$work/domain.txt" "$work/cited.txt" > "$work/ported.txt"
comm -23 "$work/domain.txt" "$work/cited.txt" > "$work/missing.txt"

total=$(wc -l < "$work/domain.txt")
ported=$(wc -l < "$work/ported.txt")
missing=$(wc -l < "$work/missing.txt")

{
  echo "# Parity inventory"
  echo
  echo "Generated by \`tiri-parity/inventory.sh\`. Do not edit by hand — edit the script, or"
  echo "port a function and rerun."
  echo
  echo "The denominator the fuzz cannot give us. A campaign's seed count describes its budget"
  echo "as much as the compositor: raising \`SCRIPT_LEN\` from 14 to 28 turned five clean seeds"
  echo "into five divergent ones without a line of layout code changing. This list does not"
  echo "move when a constant does."
  echo
  echo "\"Cited\" means tiri names the function where it implements it. It proves the rule was"
  echo "read, not that it was read correctly; the fixtures prove that. Coverage of the map,"
  echo "not of the ground."
  echo
  echo "| | |"
  echo "|---|---|"
  echo "| sway functions in the domain | $total |"
  echo "| cited in tiri | $ported |"
  echo "| not yet cited | $missing |"
  echo
  echo "Domain: \`sway/tree/{container,workspace,arrange}.c\` and the commands that reshape the"
  echo "tree — \`move\`, \`split\`, \`layout\`, \`focus\`, \`resize\`, \`fullscreen\`, \`swap\`. Excluded:"
  echo "seat device configuration, marks, scratchpad, criteria, bars, output layout."
  echo
  echo "## Cited"
  echo
  sed 's/^/- `/; s/$/`/' "$work/ported.txt"
  echo
  echo "## Not yet cited"
  echo
  echo "Not all of these need porting — some are sway plumbing with no tiri counterpart. Each"
  echo "one that does not is worth a line saying so, here or at its call site."
  echo
  sed 's/^/- `/; s/$/`/' "$work/missing.txt"
} > "$OUT"

echo "$ported of $total cited — $OUT"
